// <auto-generated />
using System;
using FuelWallet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelWallet.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621120000_DropRevokedTokensTable")]
    partial class DropRevokedTokensTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuelWallet.Domain.Entities.FuelTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AuthorizedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PumpId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RequestReference")
                        .IsUnique();

                    b.ToTable("FuelTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorizedAmount = 100m,
                            CreatedAt = new DateTime(2026, 6, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            PumpId = 1,
                            RequestReference = "SEED-REF-001",
                            RequestedAmount = 100m,
                            StationId = 101,
                            Status = "Authorized",
                            UpdatedAt = new DateTime(2026, 6, 18, 8, 0, 1, 0, DateTimeKind.Utc),
                            WalletId = "WLT-1001"
                        },
                        new
                        {
                            Id = 2,
                            AuthorizedAmount = 200m,
                            CreatedAt = new DateTime(2026, 6, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            PumpId = 2,
                            RequestReference = "SEED-REF-002",
                            RequestedAmount = 200m,
                            StationId = 102,
                            Status = "Authorized",
                            UpdatedAt = new DateTime(2026, 6, 17, 10, 0, 1, 0, DateTimeKind.Utc),
                            WalletId = "WLT-1001"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            PumpId = 3,
                            RejectionReason = "Wallet balance is insufficient for this transaction.",
                            RequestReference = "SEED-REF-003",
                            RequestedAmount = 300m,
                            StationId = 101,
                            Status = "Rejected",
                            UpdatedAt = new DateTime(2026, 6, 19, 9, 0, 0, 0, DateTimeKind.Utc),
                            WalletId = "WLT-1002"
                        },
                        new
                        {
                            Id = 4,
                            AuthorizedAmount = 80m,
                            CreatedAt = new DateTime(2026, 6, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            PumpId = 1,
                            RequestReference = "SEED-REF-004",
                            RequestedAmount = 80m,
                            StationId = 103,
                            Status = "Authorized",
                            UpdatedAt = new DateTime(2026, 6, 16, 14, 0, 1, 0, DateTimeKind.Utc),
                            WalletId = "WLT-1003"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            PumpId = 2,
                            RequestReference = "SEED-REF-005",
                            RequestedAmount = 50m,
                            StationId = 101,
                            Status = "Expired",
                            UpdatedAt = new DateTime(2026, 6, 15, 11, 2, 0, 0, DateTimeKind.Utc),
                            WalletId = "WLT-1003"
                        });
                });

            modelBuilder.Entity("FuelWallet.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$lzaqMxWYuz.RUodv.jkjVeOItX/ZbbLbgafajVghbfzEt1BvRAZh6",
                            Username = "station-api"
                        });
                });

            modelBuilder.Entity("FuelWallet.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DailyLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("WalletId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 500.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUST-001",
                            CustomerName = "Ahmed Hassan",
                            DailyLimit = 300.00m,
                            IsActive = true,
                            RowVersion = new byte[0],
                            VehiclePlate = "ABC-1234",
                            WalletId = "WLT-1001"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 50.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUST-002",
                            CustomerName = "Sara Mostafa",
                            DailyLimit = 200.00m,
                            IsActive = true,
                            RowVersion = new byte[0],
                            VehiclePlate = "XYZ-5678",
                            WalletId = "WLT-1002"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 1000.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUST-003",
                            CustomerName = "Omar Khalil",
                            DailyLimit = 100.00m,
                            IsActive = true,
                            RowVersion = new byte[0],
                            VehiclePlate = "DEF-9999",
                            WalletId = "WLT-1003"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 500.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUST-004",
                            CustomerName = "Layla Ibrahim",
                            DailyLimit = 300.00m,
                            IsActive = false,
                            RowVersion = new byte[0],
                            VehiclePlate = "GHI-4321",
                            WalletId = "WLT-1004"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
